name: Production CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_PROD }}
      
      - name: Build and deploy application to Production
        env:
          REGION: 'us-east1'
          CLUSTER: 'scooter-app-p'
          NAMESPACE: 'default' # or the appropriate namespace for production
        run: |
          # Build the Docker image
          docker build -t myapp .

          # Push the Docker image to a container registry (e.g., Docker Hub)
          docker push myusername/myapp:latest

          # Deploy the application to the Kubernetes cluster
          kubectl apply -f deployment.yaml

          # Wait for a few seconds to complete the deployment
          sleep 10

          # Make an HTTP request to the deployed application and check the HTTP status code
          response=$(curl -s -o /dev/null -w "%{http_code}" http://<ingress-url>/health)
          
          if [ $response -eq 200 ]; then
            echo "Deployment to Production is successful! HTTP status code: $response"
          else
            echo "There is an issue during the deployment to Production. HTTP status code: $response"
            exit 1
          fi
